### ISSUE TITLE
Connection refused while curl 

### ISSUE THREAD

**Issue by RiteshPuvvada** [selikapro/microservices-python#24] opened 2022-12-30 08:55 UTC
![image](https://user-images.githubusercontent.com/73629361/210052425-9594810d-101c-4864-a0e3-fa5eb4fa2e75.png)

My host's file :

![image](https://user-images.githubusercontent.com/73629361/210052480-69cc8771-7b35-44de-bd39-d6c324ebc11c.png)

**Comment by selikapro** [comment] 2023-01-09 10:43
There is not enough info here. Where is your ingress config for the gateway? If you want people to help you, please take the time to write out details about what the issue is, what you tried to do to fix it, etc. Just posting pictures just shows that you want somebody else to do all of the work for you. I'm closing this. Please open another with more details.

**Closed by selikapro** 2023-01-09 10:43 UTC
